CREATE TABLE tGlobal (
  cId INTEGER PRIMARY KEY AUTOINCREMENT,
  cKey TEXT UNIQUE,
  cValue TEXT,
  PRIMARY KEY (id)
)

INSERT INTO tGlobal (cKey, cValue) VALUES ('version', 1)

CREATE TABLE tPictures (
  cId INTEGER PRIMARY KEY AUTOINCREMENT,
  cRel_path TEXT NOT NULL,
  cUser_id INT NOT NULL,
  cQuestion TEXT,
  cUpload_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE tAnswers (
  cId INTEGER PRIMARY KEY AUTOINCREMENT,
  cPicture_id INT NOT NULL,
  cUser_id INT NOT NULL,
  cAnswer TEXT NOT NULL,
  cDate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE tUsers (
  cId INTEGER PRIMARY KEY AUTOINCREMENT,
  cName TEXT NOT NULL,
  cJoin_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
)
