CREATE TABLE global (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT UNIQUE,
  value TEXT,
  PRIMARY KEY (id)
)

INSERT INTO global (key, value) VALUES ('version', 1)

CREATE TABLE pictures (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rel_path TEXT NOT NULL,
  user_id INT NOT NULL,
  question TEXT,
  upload_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE answers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  picture_id INT NOT NULL,
  user_id INT NOT NULL,
  answer TEXT NOT NULL,
  date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY picture_id (picture_id)
)

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  join_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
)